"""initial schema

Revision ID: 0644913bc990
Revises: 
Create Date: 2026-08-31 13:16:25.395154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0644913bc990'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chat_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('lessonplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('oatutor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allow_recycle', sa.Boolean(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skilldefault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prob_mastery', sa.Float(), nullable=False),
    sa.Column('prob_transit', sa.Float(), nullable=False),
    sa.Column('prob_slip', sa.Float(), nullable=False),
    sa.Column('prob_guess', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sourcedocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INDEXED', 'FAILED', name='ingestionstatus'), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('lesson_plan_id', sa.Integer(), nullable=True),
    sa.Column('oatutor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('oer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('variabilization', sa.JSON(), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('GENERATING', 'FAILED', 'DRAFT', 'EDITED', 'EXPORT_READY', name='draftstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lessonplan.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('oatutor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('problem_type', sa.Enum('TEXT_BOX', 'MULTIPLE_CHOICE', 'GRID_INPUT', 'MATRIX_INPUT', name='problemtype'), nullable=False),
    sa.Column('answer_type', sa.Enum('ARITHMETIC', 'NUMERIC', 'STRING', name='answertype'), nullable=False),
    sa.Column('step_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_answer', sa.JSON(), nullable=True),
    sa.Column('answer_validator', sa.Enum('DEFAULT', 'SIMPLIFIED', name='answervalidator'), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('num_rows', sa.Integer(), nullable=True),
    sa.Column('num_cols', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('variabilization', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hintentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('pathway_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('oatutor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('HINT', 'SCAFFOLD', 'SOLUTION', name='hinttype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('problem_type', sa.Enum('TEXT_BOX', 'MULTIPLE_CHOICE', 'GRID_INPUT', 'MATRIX_INPUT', name='problemtype'), nullable=True),
    sa.Column('answer_type', sa.Enum('ARITHMETIC', 'NUMERIC', 'STRING', name='answertype'), nullable=True),
    sa.Column('hint_answer', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hintentry')
    op.drop_table('step')
    op.drop_table('problem')
    op.drop_table('sourcedocument')
    op.drop_table('skilldefault')
    op.drop_table('lessonplan')
    op.drop_table('project')
    # ### end Alembic commands ###
