"""add generation progress

Revision ID: 5f4f131f9b88
Revises: b5996d25f565
Create Date: 2026-09-08 12:35:43.804447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5f4f131f9b88'
down_revision: Union[str, Sequence[str], None] = 'b5996d25f565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        # server_default so the rows already in the table get a value.
        batch_op.add_column(
            sa.Column('progress_done', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('progress_total', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('progress_total')
        batch_op.drop_column('progress_done')

    # ### end Alembic commands ###
