"""add step stale flag

Revision ID: 65f36fb1dda3
Revises: c4f30a9fdc14
Create Date: 2026-09-04 14:46:33.732562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65f36fb1dda3'
down_revision: Union[str, Sequence[str], None] = 'c4f30a9fdc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step', schema=None) as batch_op:
        # server_default so existing rows get a value; new rows take it from the model.
        batch_op.add_column(
            sa.Column('stale', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.drop_column('stale')

    # ### end Alembic commands ###
