from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5996d25f565'
down_revision: Union[str, Sequence[str], None] = '65f36fb1dda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generationrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('request_snapshot', sa.JSON(), nullable=True),
    sa.Column('num_slots', sa.Integer(), nullable=False),
    sa.Column('num_alternatives', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('GENERATING', 'READY', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutorcontext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('curricular_placement', sa.JSON(), nullable=True),
    sa.Column('prior_knowledge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('known_difficulties', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('knowledge_type', sa.Enum('FACT', 'RULE', 'PRINCIPLE', name='knowledgetype'), nullable=False),
    sa.Column('learning_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tutor_roles', sa.JSON(), nullable=True),
    sa.Column('feedback_mode', sa.Enum('CORRECTIVE', 'IMPLICIT', name='feedbackmode'), nullable=False),
    sa.Column('scope', sa.Enum('ADDITION', 'PARTIAL', 'FULL', name='tutorscope'), nullable=False),
    sa.Column('instructional_history', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('representations', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('terminology', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('heterogeneity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teacher_intents', sa.JSON(), nullable=True),
    sa.Column('teacher_intent_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_work', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goal_critique', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.Integer(), nullable=True))
        # server_default so the existing rows get a value; new rows take the model's.
        batch_op.add_column(
            sa.Column('slot_index', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('alternative_index', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.create_foreign_key(
            'fk_problem_run_id', 'generationrun', ['run_id'], ['id'], ondelete='SET NULL'
        )

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'study_condition',
                sa.Enum('CONTROL', 'CONTEXT', 'REVIEW', 'CONTEXT_REVIEW', name='studycondition'),
                nullable=False,
                server_default='CONTEXT_REVIEW',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('study_condition')

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_constraint('fk_problem_run_id', type_='foreignkey')
        batch_op.drop_column('alternative_index')
        batch_op.drop_column('slot_index')
        batch_op.drop_column('run_id')

    op.drop_table('tutorcontext')
    op.drop_table('generationrun')
    # ### end Alembic commands ###
