"""add hint choices

Revision ID: c4f30a9fdc14
Revises: 99e3b52176b3
Create Date: 2026-09-03 11:45:19.399238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4f30a9fdc14'
down_revision: Union[str, Sequence[str], None] = '99e3b52176b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hintentry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choices', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hintentry', schema=None) as batch_op:
        batch_op.drop_column('choices')

    # ### end Alembic commands ###
