"""add ingestion progress

Revision ID: ff5c675a5348
Revises: a3d21f0b7c48
Create Date: 2026-09-09 14:44:54.938279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5c675a5348'
down_revision: Union[str, Sequence[str], None] = 'a3d21f0b7c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sourcedocument', schema=None) as batch_op:
        # server_default so documents uploaded before this get a value.
        batch_op.add_column(
            sa.Column('progress_done', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('progress_total', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sourcedocument', schema=None) as batch_op:
        batch_op.drop_column('progress_total')
        batch_op.drop_column('progress_done')

    # ### end Alembic commands ###
